"""Add vehicle fuel log table

Revision ID: add_vehicle_fuel_logs
Revises: add_vehicle_service_logs
Create Date: 2024-05-10

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'add_vehicle_fuel_logs'
down_revision = 'add_vehicle_service_logs'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_fuel_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=True),
        sa.Column('vehicle_id', sa.Integer(), nullable=False),
        sa.Column('fueling_date', sa.Date(), nullable=False),
        sa.Column('odometer_reading', sa.Integer(), nullable=False),
        sa.Column('fuel_liters', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('fuel_price_per_liter', sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('fuel_station', sa.String(length=200), nullable=True),
        sa.Column('fuel_type', sa.String(length=20), nullable=True),
        sa.Column('driver_id', sa.Integer(), nullable=True),
        sa.Column('payment_method', sa.String(length=50), nullable=True),
        sa.Column('receipt_number', sa.String(length=100), nullable=True),
        sa.Column('receipt_path', sa.String(length=500), nullable=True),
        sa.Column('distance_since_last', sa.Integer(), nullable=True),
        sa.Column('efficiency_km_per_liter', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('cost_per_km', sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_fuel_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_fuel_logs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_fuel_logs_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_fuel_logs')
    # ### end Alembic commands ###
