"""Add vehicle service logs and schedules tables

Revision ID: add_vehicle_service_logs
Revises: 4abb0d02bd1c
Create Date: 2024-05-10

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'add_vehicle_service_logs'
down_revision = '4abb0d02bd1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_service_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=True),
        sa.Column('vehicle_id', sa.Integer(), nullable=False),
        sa.Column('service_date', sa.Date(), nullable=False),
        sa.Column('service_type', sa.String(length=50), nullable=False),
        sa.Column('service_description', sa.Text(), nullable=True),
        sa.Column('odometer_reading', sa.Integer(), nullable=True),
        sa.Column('garage_name', sa.String(length=200), nullable=True),
        sa.Column('garage_contact', sa.String(length=20), nullable=True),
        sa.Column('garage_address', sa.Text(), nullable=True),
        sa.Column('parts_replaced', sa.Text(), nullable=True),
        sa.Column('labor_cost', sa.Numeric(precision=10, scale=2), nullable=True, server_default='0'),
        sa.Column('parts_cost', sa.Numeric(precision=10, scale=2), nullable=True, server_default='0'),
        sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True, server_default='0'),
        sa.Column('invoice_number', sa.String(length=100), nullable=True),
        sa.Column('invoice_path', sa.String(length=500), nullable=True),
        sa.Column('next_service_date', sa.Date(), nullable=True),
        sa.Column('next_service_km', sa.Integer(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_service_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_service_logs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_service_logs_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('vehicle_service_schedules',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=True),
        sa.Column('vehicle_type', sa.String(length=50), nullable=True),
        sa.Column('service_type', sa.String(length=50), nullable=True),
        sa.Column('interval_months', sa.Integer(), nullable=True),
        sa.Column('interval_km', sa.Integer(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_service_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_service_schedules_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_service_schedules')
    op.drop_table('vehicle_service_logs')
    # ### end Alembic commands ###
